cp ${VARNISH_CLIENT_LOG} ${VARNISH_CLIENT_LOG_ROTATE}$(date +_%Y%m%d) && > ${VARNISH_CLIENT_LOG}
kill -SIGHUP $(cat ${VARNISH_CLIENT_LOG_PID})

cp ${VARNISH_BACKEND_LOG} ${VARNISH_BACKEND_LOG_ROTATE}$(date +_%Y%m%d) && > ${VARNISH_BACKEND_LOG}
kill -SIGHUP $(cat ${VARNISH_BACKEND_LOG_PID})